name: Processar Indicadores

on:
  push:
    branches:
      - main  # Executa ao enviar código para a branch principal

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib

    - name: Executar o script de indicadores
      run: python indicador.py

    - name: Fazer upload dos arquivos de saída
      uses: actions/upload-artifact@v2
      with:
        name: resultados
        path: output/
